### ISSUE TITLE
[Move to Google Docs]

### ISSUE THREAD

**Issue by KendallDoesCoding** [geerlingguy/youtube#2]
In my opinion, this will make better sense in a Google Docs as there isn't any need of any code for this, right?

**Comment by TechStudent10** [comment]
> This repository is a home for my YouTube production process, my thoughts on video creation and workflows, and sometimes stores things related to channel videos or series, if the work doesn't fit better in some other repository.

This place is supposed to be an open place for his video ideas that don't fit in any other repos.

**Comment by KendallDoesCoding** [comment]
> > This repository is a home for my YouTube production process, my thoughts on video creation and workflows, and sometimes stores things related to channel videos or series, if the work doesn't fit better in some other repository.
> 
> This place is supposed to be an open place for his video ideas that don't fit in any other repos.

Oh ok

**Comment by geerlingguy** [comment]
Heh, yep. And I will be using issues and discussions to work on future ideas for workflow and studio improvements, etc. So it won't really fit as a Google Doc. The README is one tiny part of the project.

**Comment by KendallDoesCoding** [comment]
> Heh, yep. And I will be using issues and discussions to work on future ideas for workflow and studio improvements, etc. So it won't really fit as a Google Doc. The README is one tiny part of the project.

Oh, now I understand much better... Thanks... Yeah, it makes sense to keep it as a repo, instead of a Google Doc.

**Comment by TechStudent10** [comment]
It also allows the community to help solve issues in particular videos.
