### ISSUE TITLE
DietPi review

### ISSUE THREAD

**Issue by Scream85** [geerlingguy/youtube#9]
Hi Jeff,
I would like to suggest the review of DeitPi on your channel. It is a great lightweight alternative to the "vanilla" Raspberry Pi OS, still based on Debian. Originally, I found it when tried to find a compatible OS for my NanoPi NEO Air.

https://dietpi.com
https://github.com/MichaIng/DietPi

Thank you!

**Comment by geerlingguy** [comment]
Thanks; this repo is more for general channel-related work (e.g. how I make videos, that sort of thing). I am available on Twitter/Mastodon/Email/elsewhere for general inquiries.

I don't plan on covering DietPi any time too soon, as my needs are covered by Pi OS and Ubuntu, usually.
